language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- CI=false npm run build
- npm test
- curl "https://dhs-hall-of-fame.herokuapp.com/$SECRET_UPDATE_KEY"
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: TXpkAfp/xNtO8QbDQClw7Ed66HmM8AAZc8EWN6uT7N29TES0G5TPxW5BJyuDwiUMUgjiXAjFvEYMVWljL7klLyFDsACU2m1/YxVcfES835qOVbkP3zB1OFGc4bd+tC0bStwE6Xf422lZWwLfwrZHnWBgEGFN/K6qMIP3q6IJTrnzyfElyODmjHfkTJ7BWigmMFB4MzEWt26pYXR6MssDV6F425pncOBY0zOYA1tUFIBjOUNn6/6ah0DNKpbPZBz5S1svmk6rrss/RSDkI00xhndhFonkEjVXTy58Dpia24LL9Qi+1AeMEuH29ahnlm0tsHKIMt7s6/d2KZ5TdNZnNXSUI1cbSZgpmYC9P8jgQRsKYCNh/kiSdsCzyQ17yj9j9fBCd+jF3vdkPuejHpZoBvyaohRiuczt6Zhuw6RTIkIwgYAVkEXChXYGwWwaNO+cFYxhvL1ZOtX4wsJtWJmeQSkeFR3a8uYC41nghX+jA6jZOllp4ToulispT9/FTTRmuV7xP9iPELhHn5UlAZ83rVMalarbwFvmAV+CGSimRt9PynWzheoVgjn3u/gkgECOKK9bm25aGiylM9md3MHgVqhHM+lffepspoNrZloOtjb8Aik5lKUVtBSsO8P4+WgDzHZo2p6tACm5ZJT71UiLpLJRsypYZ361d+e/B3nWCfA=
  local_dir: build
  repo: desotohs/hall-of-fame
  on:
    branch: master
env:
  global:
    secure: KmQjxRPm6BAkEzMySWrp+scH5vTQQficOehoEHx3i2uh+FUFkCo0+/skW9AqosfUlr1Gk5jgn90QNtrYw9MHMA9BvszsjMARje3/7PEGQ7VqBXQFmlq7dGxmbTahvAQXYxXchcfM6ROoSpSelRVr3reAujFapwWPY5+TK90Iyl0pnvumTyE6uCVrcLhOTDDIG+IuKPclHqXhlkw4qQJiO4w8XpFfFH4r8R8pBaw63VeX3RfsJXUCvtiSZ14oYQf47fZWrO5FIgbJ1yEETSh24UFeqHcISZbZfLQ6czVFtnex4RcqioZ/DEJ7CCi7UEprE42E39sPkWPN3OdOGLxIrUaQp3VNs1CV8YPsIF7/SEpOPsBA38c+P10kL9Arwtf53Z72gFqMrQL+qYXLpdITfYIWSXcPyi83jx4R+WP8KztXMMy8oyPEE2vbna4i/ivhSIovEEiS0GxiLUhv26x6m+jwBaykqTJFL4Gi9cDIbE/1mQCMyefiAYLui1+6LI+cV6TKVlGSLSz4rt8Jc2tB5nucJZ26VseIyyKX6sDx3HdT+jGsXHMupsqhalHMcpL0jAQkEKMaK2ZYmE7Gqlf3iRRNCRyTTSQ2AFIsYB4LebHbHHil4QHu/X3MzV+IyRdvTihEN6MySCnQD3SVDNcR7P0KBMNVLHp20OacO+T2Ank=
